// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartTerraAPI;

namespace SmartTerraAPI.Migrations
{
    [DbContext(typeof(SmartTerraDbContext))]
    partial class SmartTerraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("SmartTerraAPI.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SmartTerra v1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 101,
                            Name = "ROBOLab test device 1",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SmartTerraAPI.Models.DeviceJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Done")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExecutionTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("JobId");

                    b.ToTable("DeviceJobs");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Body = "angle: 10, speed: 2",
                            CreatedDate = new DateTime(2021, 4, 26, 18, 40, 15, 139, DateTimeKind.Local).AddTicks(8040),
                            DeviceId = 101,
                            Done = false,
                            ExecutionTime = new DateTime(2021, 4, 26, 18, 40, 15, 121, DateTimeKind.Local).AddTicks(6340),
                            JobId = 5
                        },
                        new
                        {
                            Id = 12,
                            Body = "angle: 50, speed: 3",
                            CreatedDate = new DateTime(2021, 4, 26, 18, 40, 15, 140, DateTimeKind.Local).AddTicks(420),
                            DeviceId = 101,
                            Done = false,
                            ExecutionTime = new DateTime(2021, 4, 26, 18, 40, 15, 140, DateTimeKind.Local).AddTicks(250),
                            JobId = 6
                        },
                        new
                        {
                            Id = 13,
                            Body = "angle: 25, speed: 1",
                            CreatedDate = new DateTime(2021, 4, 26, 18, 40, 15, 140, DateTimeKind.Local).AddTicks(870),
                            DeviceId = 101,
                            Done = false,
                            ExecutionTime = new DateTime(2021, 4, 26, 18, 40, 15, 140, DateTimeKind.Local).AddTicks(860),
                            JobId = 6
                        });
                });

            modelBuilder.Entity("SmartTerraAPI.Models.DeviceProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HeatIndex")
                        .HasColumnType("REAL");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<double>("LEDBrightness")
                        .HasColumnType("REAL");

                    b.Property<string>("LEDHexColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SoilMoisturePercentage")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<bool>("isLiquidLevelSufficient")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceProperties");
                });

            modelBuilder.Entity("SmartTerraAPI.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Turn on the LED strip and set color of the LEDs .",
                            Name = "TurnOnLED",
                            Type = "LED"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Turn off the LED strip.",
                            Name = "TurnOffLED",
                            Type = "LED"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Turn on the water pump for given period of time.",
                            Name = "TurnOnWaterPump",
                            Type = "PUMP"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Turn on rainbow.",
                            Name = "Rainbow",
                            Type = "LED"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Turn right description.",
                            Name = "TurnRight",
                            Type = "ROBOTIC_ARM"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Turn left description.",
                            Name = "TurnLeft",
                            Type = "ROBOTIC_ARM"
                        });
                });

            modelBuilder.Entity("SmartTerraAPI.Models.Mode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("HourOfDawn")
                        .HasColumnType("TEXT");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("TwilightHour")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("Modes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceId = 1,
                            HourOfDawn = new TimeSpan(0, 0, 0, 0, 0),
                            Humidity = 0.0,
                            IsOn = false,
                            Name = "Terrarium mode 1",
                            Temperature = 25.0,
                            TwilightHour = new TimeSpan(0, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("SmartTerraAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ola@email.com",
                            Login = "ola",
                            Password = "pass1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "robolab@email.com",
                            Login = "robolab",
                            Password = "pass1"
                        });
                });

            modelBuilder.Entity("SmartTerraAPI.Models.Device", b =>
                {
                    b.HasOne("SmartTerraAPI.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SmartTerraAPI.Models.DeviceJob", b =>
                {
                    b.HasOne("SmartTerraAPI.Models.Device", "Device")
                        .WithMany("DeviceJobs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartTerraAPI.Models.Job", "Job")
                        .WithMany("DeviceJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartTerraAPI.Models.DeviceProperties", b =>
                {
                    b.HasOne("SmartTerraAPI.Models.Device", "Device")
                        .WithMany("DeviceProperties")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartTerraAPI.Models.Mode", b =>
                {
                    b.HasOne("SmartTerraAPI.Models.Device", "Device")
                        .WithOne("Mode")
                        .HasForeignKey("SmartTerraAPI.Models.Mode", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
